name: BO3Tools
main: nl.rutgerkok.bo3tools.BO3Tools
version: 0.1
authors: ["Rutger Kok"]
depends: ["TerrainControl", "WorldEdit"]
description: Bukkit plugin to help you working with the BO3 objects.
permissions:
  bo3tools.all:
    description: Use all BO3 tools
    default: op
    children:
      bo3tools.export: true
  bo3tools.export:
    description: Export BO3 tools.
commands:
  exportbo3:
    description: "Export a WorldEdit selection to a BO3, ignoring all air blocks."
    usage: "/<command> <bo3name> [--includeair]"
    aliases: [export]